type Todo {
    id: ID!
    title: String!
    done: Boolean!
}

input TodoInput {
    id: ID!
    title: String!
    done: Boolean!
}

i

type Query {
    getTodos: [Todo]
}

type Mutation {
    addTodo(todo: TodoInput!): Todo
    updateTodo(todo : TodoInput! ): Todo
}

type Subscription {
    onAddProduct: Todo
    @aws_subscribe(mutations : ["addTodo"])
}